### ISSUE TITLE
master.jinja template doesn't highlight tabs in navbar

### ISSUE THREAD

**Issue by devilicecream** [TurboGears/tg2devtools#10]
There's a little bug in the master template for Jinja2, that assigns the `active` class to the anchor inside the `li` element, instead of the `li` itself in the top navbar. 
The result is that the tabs in the top navbar never get highlighted.

**Comment by amol-** [comment]
I'll gladly merge a pull request if you can submit one. The jinja template is an external contribution I rarely use, so I really appreciate any fix for it jinja users can contribute.
