### ISSUE TITLE
Updated to WebTest 2

### ISSUE THREAD

**Issue by Amwam** [TurboGears/tg2devtools#7]
We're currently running into issue when installing tgdevtools, as this package attempts to install WebTest < 2, where as we are attempting to use WebTest > 2. 

I've run the tests for this package using WebTest 2, and have found no issues.

I was thinking of a submitting a PR to update this, but am unsure if there are other implications of using WebTest 2, with regards to the rest of the TG stack?

Thanks.

**Comment by amol-** [comment]
The choice to stick with `WebTest<2` is mostly related to the far smaller footprint of WebTest 1 and the higher amount of dependencies required by webtest2 for little to no benefits.

The tests are compatible with both WebTest1 and WebTest2 so work with both. I'm not sure we want to introduce 4-5 new dependencies for the same package that worked fine without them. We should probably look for a way to let the user decide but provide 1.X by default. 

Probably removing webtest as a dependency on tg.devtools and having it only as a dependency of the application itself would be the best solution. As the user would be able to change the required version however he prefers.

**Comment by amol-** [comment]
New template starts with most recent version of WebTest
